const theme = {
  colors: {
    body: '#FBFFFE',
    blue: '#355c7d',
    green: '#13ab89',
    orange: '#d76e78',
    teal: '#2aa1af',
    grey: '#708090',
    modal: '#b1bec7',
  },
  font: 'Montserrat Latin 700',
  fontFamily: 'Nunito Sans sans-serif',
  fontFamilyNav: 'Montserrat sans-serif',
  fontFamilyBtn: 'Poppins, sans-serif',
  subsets: 'latin',
  variants: '400, 700, 100, 200',
  fontDisplay: 'auto',
  footerSize: '1.1rem',
  navWeight: '100',
  borderRadiusBtn: '8px',
  borderRadiusCard: '4px',
  transition: 'ease-in-out',
  transform: 'scale(1)',
  boxShadow: '0 5px 9px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.2)',
  gridTemplateColumnsDesk: 'repeat(3, 1fr)',
  gridTemplateColumnsMob9: 'repeat(2, 1fr)',
  gridTemplateColumnsMob6: '1fr',
  gridTemplateRows: '8fr',
  gap: '1.2rem 1.2rem',
};

export default theme;
